import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.course.createMany({
    skipDuplicates: true,
    data: [
      // ─── 장병e음 강의 (10개) ───────────────────────────────────────────────
      {
        title: '장병e음 토익 집중과정',
        source: 'JANGBYEONGEEUM',
        category: 'LANGUAGE',
        targetGoalType: 'STUDY',
        description: '군 복무 중 토익 점수 향상을 위한 집중 강의. RC/LC 전 영역 커버.',
        durationMinutes: 60,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['토익', '영어', '청취', 'RC', 'LC']),
      },
      {
        title: '장병e음 컴퓨터활용능력 2급',
        source: 'JANGBYEONGEEUM',
        category: 'IT',
        targetGoalType: 'CERTIFICATE',
        description: '컴활 2급 자격증 취득을 위한 기초~실전 강의.',
        durationMinutes: 90,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['컴활', '자격증', '엑셀', '스프레드시트']),
      },
      {
        title: '장병e음 한국사능력검정시험',
        source: 'JANGBYEONGEEUM',
        category: 'CERTIFICATE',
        targetGoalType: 'CERTIFICATE',
        description: '한국사 1~2급 대비 강의. 군 가산점 취득 가능.',
        durationMinutes: 45,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['한국사', '자격증', '가산점']),
      },
      {
        title: '장병e음 독서 논술 특강',
        source: 'JANGBYEONGEEUM',
        category: 'LANGUAGE',
        targetGoalType: 'READING',
        description: '독해력 향상과 논술 작성 능력을 키우는 강의.',
        durationMinutes: 30,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['독서', '논술', '독해']),
      },
      {
        title: '장병e음 체력단련 프로그램',
        source: 'JANGBYEONGEEUM',
        category: 'EXERCISE',
        targetGoalType: 'EXERCISE',
        description: '체계적인 군 체력 향상 프로그램. 코어, 유산소 포함.',
        durationMinutes: 40,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['운동', '체력', '헬스', '코어']),
      },
      {
        title: '장병e음 TOEIC Speaking 특강',
        source: 'JANGBYEONGEEUM',
        category: 'LANGUAGE',
        targetGoalType: 'STUDY',
        description: '토익 스피킹 점수 향상을 위한 실전 말하기 훈련 강의. Level 6~7 목표.',
        durationMinutes: 60,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['토익스피킹', '영어회화', '스피킹', '말하기']),
      },
      {
        title: '장병e음 워드프로세서 1급',
        source: 'JANGBYEONGEEUM',
        category: 'IT',
        targetGoalType: 'CERTIFICATE',
        description: '워드프로세서 1급 자격증 취득을 위한 문서 작성 능력 향상 강의.',
        durationMinutes: 60,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['워드프로세서', '자격증', '문서작성', 'OA']),
      },
      {
        title: '장병e음 영어 회화 기초',
        source: 'JANGBYEONGEEUM',
        category: 'LANGUAGE',
        targetGoalType: 'STUDY',
        description: '전역 후 취업·유학에 대비한 기초 영어 회화 강의. 일상 표현 중심.',
        durationMinutes: 30,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['영어회화', '영어', '기초', '생활영어']),
      },
      {
        title: '장병e음 리더십 특강',
        source: 'JANGBYEONGEEUM',
        category: 'LEADERSHIP',
        targetGoalType: 'OTHER',
        description: '군 조직에서의 리더십 역량 강화를 위한 특강. 팀워크·의사결정 훈련.',
        durationMinutes: 60,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['리더십', '조직관리', '팀워크', '의사소통']),
      },
      {
        title: '장병e음 재테크·금융 기초',
        source: 'JANGBYEONGEEUM',
        category: 'OTHER',
        targetGoalType: 'STUDY',
        description: '군 적금, 적립식 펀드, 절세 등 병사를 위한 실용 금융 기초 강의.',
        durationMinutes: 45,
        url: 'https://www.jbemc.mil.kr',
        tags: JSON.stringify(['재테크', '금융', '적금', '투자', '절세']),
      },

      // ─── 국방전직교육원 (7개) ──────────────────────────────────────────────
      {
        title: '국방전직교육원 취업 특강 — 자기소개서·면접',
        source: 'DEFENSE_TRANSITION',
        category: 'LEADERSHIP',
        targetGoalType: null,
        description: '전역 후 민간 취업을 준비하는 병사를 위한 자기소개서 작성 및 면접 특강.',
        durationMinutes: 120,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['취업', '자기소개서', '면접', '전직']),
      },
      {
        title: '국방전직교육원 창업 교육 과정',
        source: 'DEFENSE_TRANSITION',
        category: 'LEADERSHIP',
        targetGoalType: null,
        description: '군 전역 후 창업을 희망하는 병사를 위한 창업 기초 교육.',
        durationMinutes: 180,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['창업', '스타트업', '비즈니스']),
      },
      {
        title: '국방전직교육원 IT 직무교육',
        source: 'DEFENSE_TRANSITION',
        category: 'IT',
        targetGoalType: 'CODING',
        description: '전역 후 IT 분야 취업을 위한 프로그래밍 기초 직무교육.',
        durationMinutes: 120,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['IT', '프로그래밍', '코딩', '취업']),
      },
      {
        title: '국방전직교육원 경찰·소방 공무원 준비 과정',
        source: 'DEFENSE_TRANSITION',
        category: 'OTHER',
        targetGoalType: null,
        description: '전역 후 경찰·소방 공무원 시험을 준비하는 병사를 위한 전문 교육 과정.',
        durationMinutes: 90,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['공무원', '경찰', '소방', '시험준비']),
      },
      {
        title: '국방전직교육원 용접·기계 기술 직무교육',
        source: 'DEFENSE_TRANSITION',
        category: 'OTHER',
        targetGoalType: 'CERTIFICATE',
        description: '용접기능사, 기계조립기능사 등 기술 자격증 취득을 위한 실습 중심 교육.',
        durationMinutes: 120,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['용접', '기계', '기능사', '자격증', '기술직']),
      },
      {
        title: '국방전직교육원 드론 조종사 자격 과정',
        source: 'DEFENSE_TRANSITION',
        category: 'CERTIFICATE',
        targetGoalType: 'CERTIFICATE',
        description: '초경량비행장치 조종자 자격증 취득을 위한 드론 이론 및 실습 교육.',
        durationMinutes: 90,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['드론', '자격증', '초경량비행', '조종사']),
      },
      {
        title: '국방전직교육원 요리·바리스타 직무교육',
        source: 'DEFENSE_TRANSITION',
        category: 'OTHER',
        targetGoalType: null,
        description: '전역 후 외식업·카페 창업을 원하는 병사를 위한 조리·바리스타 실습 과정.',
        durationMinutes: 180,
        url: 'https://www.kdemtc.or.kr',
        tags: JSON.stringify(['요리', '바리스타', '카페', '조리', '창업']),
      },

      // ─── K-MOOC 강의 (8개) ────────────────────────────────────────────────
      {
        title: 'K-MOOC 파이썬 프로그래밍 기초',
        source: 'K_MOOC',
        category: 'IT',
        targetGoalType: 'CODING',
        description: '대학 수준 파이썬 입문 강의. 서울대·연세대 교수진 참여.',
        durationMinutes: 60,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['파이썬', '코딩', '프로그래밍', 'AI']),
      },
      {
        title: 'K-MOOC AI 기초와 윤리',
        source: 'K_MOOC',
        category: 'IT',
        targetGoalType: 'STUDY',
        description: '인공지능의 기초 개념과 사회적 영향, AI 윤리를 다루는 강의.',
        durationMinutes: 45,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['AI', '인공지능', '윤리', '기초']),
      },
      {
        title: 'K-MOOC 데이터 분석 입문',
        source: 'K_MOOC',
        category: 'IT',
        targetGoalType: 'CODING',
        description: '엑셀·파이썬을 활용한 데이터 분석 기초. 취업·대학원 준비에 유용.',
        durationMinutes: 60,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['데이터분석', '통계', '파이썬', '엑셀']),
      },
      {
        title: 'K-MOOC 영어 글쓰기 기초',
        source: 'K_MOOC',
        category: 'LANGUAGE',
        targetGoalType: 'STUDY',
        description: '영어 에세이·이메일 작성 능력을 키우는 실용 영어 글쓰기 강의.',
        durationMinutes: 45,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['영어', '영작문', '글쓰기', '에세이']),
      },
      {
        title: 'K-MOOC 경영학 원론',
        source: 'K_MOOC',
        category: 'LEADERSHIP',
        targetGoalType: 'STUDY',
        description: '전역 후 취업·창업에 필요한 경영학 기초 개념. 마케팅·회계·인사 포함.',
        durationMinutes: 60,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['경영학', '마케팅', '비즈니스', '취업준비']),
      },
      {
        title: 'K-MOOC 심리학 개론',
        source: 'K_MOOC',
        category: 'OTHER',
        targetGoalType: 'READING',
        description: '인간 행동의 이해를 위한 심리학 기초. 자기 이해와 대인 관계에 도움.',
        durationMinutes: 45,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['심리학', '자기계발', '인간관계', '행동과학']),
      },
      {
        title: 'K-MOOC 미래 직업 탐색',
        source: 'K_MOOC',
        category: 'LEADERSHIP',
        targetGoalType: 'OTHER',
        description: '4차 산업혁명 시대의 유망 직업과 진로를 탐색하는 강의. 전역 준비 병사 추천.',
        durationMinutes: 30,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['진로', '직업', '미래', '4차산업']),
      },
      {
        title: 'K-MOOC 수학 기초 (미적분·선형대수)',
        source: 'K_MOOC',
        category: 'OTHER',
        targetGoalType: 'STUDY',
        description: '공대 진학·AI 공부에 필요한 수학 기초. 미적분·벡터·행렬 핵심 정리.',
        durationMinutes: 60,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['수학', '미적분', '선형대수', '공학', 'AI기초']),
      },
      {
        title: 'K-MOOC UI/UX 디자인 기초',
        source: 'K_MOOC',
        category: 'IT',
        targetGoalType: 'OTHER',
        description: '사용자 중심 디자인 원칙과 프로토타이핑 툴 사용법. 창업 준비 병사 추천.',
        durationMinutes: 45,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['UI', 'UX', '디자인', '프로토타이핑', '창업']),
      },
      {
        title: 'K-MOOC 건강과 웰빙 관리',
        source: 'K_MOOC',
        category: 'EXERCISE',
        targetGoalType: 'EXERCISE',
        description: '스트레스 관리와 건강 유지 방법을 배우는 강의. 군 생활 적응에 도움.',
        durationMinutes: 30,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['건강', '웰빙', '스트레스관리', '정신건강']),
      },
      {
        title: 'K-MOOC 환경과 지속가능성',
        source: 'K_MOOC',
        category: 'OTHER',
        targetGoalType: 'STUDY',
        description: '기후변화와 지속가능한 발전 목표를 이해하는 강의. 사회적 책임 교육.',
        durationMinutes: 45,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['환경', '지속가능성', '기후변화', '사회적책임']),
      },
      {
        title: 'K-MOOC 한국 문화와 역사',
        source: 'K_MOOC',
        category: 'OTHER',
        targetGoalType: 'READING',
        description: '한국의 전통 문화와 근현대사를 이해하는 종합 강의. 자기계발에 유용.',
        durationMinutes: 60,
        url: 'https://www.kmooc.kr',
        tags: JSON.stringify(['한국문화', '역사', '전통', '자기계발']),
      },
    ],
  });
  console.log('✅ 강의 시드 데이터 입력 완료 (총 30건)');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
