spring:
  profiles:
    active: local

  jpa:
    open-in-view: false

server:
  port: ${PORT:8080}

jwt:
  secret: aBQwIbBXTkXqsaKcPWNoZvS/GeBeVok+xRXo4jXgmYeju8tg1BIBHhJ3oBtnG0bI
  access-token-expiration: 3600000       # 1시간 (ms)
  refresh-token-expiration: 604800000    # 7일 (ms)

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
